name: Modify & Improve Blog Information Report（修改和完善博客信息）
description: 修改和完善博客信息
title: "[Modify & Improve]-<博客名称>-<博客的 idx>"
labels:
  - Modify & Improve（修改和完善）
assignees:
  - MYXXTS
  - aquausora
  - gtxykn0504
  - linlinzzo
  - Lafcadia
body:
  - type: markdown
    attributes:
      value: |
        ## zhblogs Modify & Improve Blog Information Report 模板
        ---
        ***请按照已给出的标题格式替换并补充 <> 内部的信息***
        请在反馈之前在 [Issues](https://github.com/zh-blogs/blog-daohang/issues) list 中搜索是否已经有人反馈过同一博客的问题（请善用标签）。
        请尽可能在已有的 Issue 下进行跟进，允许 Reopen Issue 进行补充反馈。
        请按照下面的模板填写，方便我们更快的定位问题。
  - type: input
    id: blog_name
    attributes:
      label: 博客名称
      description: 请填写博客名称
      placeholder: 博客名称
    validations: 
      required: true
  - type: input
    id: blog_idx
    attributes:
      label: 博客 idx
      description: 请填写博客的 idx
      placeholder: 博客的 idx
    validations: 
      required: true
  - type: input
    id: blog_url
    attributes:
      label: 博客 URL
      description: 请填写博客的 URL
      placeholder: 博客的 URL
    validations: 
      required: true
  - type: dropdown
    id: blog_modify_improve_type
    attributes:
      label: 修改或完善的字段
      description: 请选择博客需要修改或完善的字段
      multiple: true
      options:
        - 博客名称
        - 博客 URL
        - 博客描述
        - 博客 RSS 订阅地址
        - 博客网站地图（SiteMap）地址 
        - 博客所用程序（架构）
        - 博客标签（Tag）
    validations:
      required: true
  - type: textarea
    id: blog_modify_improve_content
    attributes:
      label: 修改或完善的内容
      description: |
        请按照上方选择的字段填写需要修改或完善的内容，每行一个字段
        示例：如果选择了博客名称和博客描述，那么请按照以下格式填写：
        博客名称：XXX
        博客描述：XXX
      placeholder: 请填写博客需要修改和完善的内容
    validations: 
      required: true