name: Selected Blog Application（精选博客申请）
description: 修改和完善博客信息
title: "[Selected]-<博客名称>-<博客的 idx>"
labels:
  - Selected Blog（精选博客）
assignees:
  - MYXXTS
  - aquausora
  - gtxykn0504
  - linlinzzo
  - Lafcadia
body:
  - type: markdown
    attributes:
      value: |
        ## zhblogs Modify & Improve Blog Information Report 模板
        ---
        ***请按照已给出的标题格式替换并补充 <> 内部的信息***
        请在反馈之前在 [Issues](https://github.com/zh-blogs/blog-daohang/issues) list 中搜索是否已经有人反馈过同一博客的问题（请善用标签）。
        请尽可能在已有的 Issue 下进行跟进，允许 Reopen Issue 进行补充反馈。
        请按照下面的模板填写，方便我们更快的定位问题。
  - type: input
    id: blog_name
    attributes:
      label: 博客名称
      description: 请填写博客名称
      placeholder: 博客名称
    validations: 
      required: true
  - type: input
    id: blog_idx
    attributes:
      label: 博客 idx
      description: 请填写博客的 idx
      placeholder: 博客的 idx
    validations: 
      required: true
  - type: input
    id: blog_url
    attributes:
      label: 博客 URL
      description: 请填写博客的 URL
      placeholder: 博客的 URL
    validations: 
      required: true
  - type: textarea
    id: selected_blog_application_content
    attributes:
      label: 申请原因
      description: 请填写申请精选博客的原因
      placeholder: 请填写申请原因
    validations: 
      required: true